version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    secrets:
      - openai_api_key
      - openai_assistant_id
      - admin_api_key
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - web

networks:
  web:
    driver: bridge

secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  openai_assistant_id:
    file: ./secrets/openai_assistant_id.txt
  admin_api_key:
    file: ./secrets/admin_api_key.txt 