version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osprey_web_prod
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: osprey_labs
      DB_USER: osprey_user
      DB_PASSWORD: osprey_secure_password_2024
      NEXTAUTH_SECRET: your-nextauth-secret-here
      NEXTAUTH_URL: http://localhost:3000
      OPENAI_API_KEY: your-openai-api-key-here
    ports:
      - "80:3000"
    networks:
      - osprey_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  osprey_network:
    driver: bridge 